#pragma config(Sensor, in1,    lineCL,         sensorLineFollower)
#pragma config(Sensor, in2,    lineCR,         sensorLineFollower)
#pragma config(Sensor, in3,    lineBL,         sensorLineFollower)
#pragma config(Sensor, in4,    lineBR,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  flywheelEnc1,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  flywheelEnc2,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  encFL,          sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  encFR,          sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  encBL,          sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encBR,          sensorQuadEncoder)
#pragma config(Motor,  port1,           lift1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveFL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveFR,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveBL,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           driveBR,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           flywheel1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           flywheel2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           hopper,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          lift2,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "util.c"

#include "Vex_Competition_Includes.c" //Main competition background code...do not modify!

// CHANGE THIS TO 1/0 TO ENABLE/DISABLE PID CONTROL
#define USE_PID 0
#if USE_PID
  #define IF_PID(code) code
  #define IF_NPID(code)
#else
  #define IF_PID(code)
  #define IF_NPID(code) code
#endif


//	Pre-Autonomous Code
void pre_auton() {
	bStopTasksBetweenModes = true;
	// stuff??....
}





//	Autonomous Task
task autonomous() {
	return; // FOR TESTINGGGNNGJDSHFIEUISF

	motorControlInit();
	flywheelSpeed = 64;

	// main loop
	while (true) {
		IF_PID(motorControlUpdate();)
		IF_NPID(motor[flywheel1] = motor[flywheel2] = flywheelSpeed;)

		motor[intake] = motor[hopper] = 64;
	}
}





//	User Control Task
task usercontrol() {
	motorControlInit();
	flywheelSpeed = 64;

	bool prev8U = false, prev8D = false; // used for detecting when buttons are pressed (vs held down)

	// main loop
	while (true) {
		IF_PID(motorControlUpdate();)
		//// CONTROL DRIVE WHEELS WITH JOYSTICKS ////
		{
			int fl, fr, bl, br;
			bool lineMode = (bool)vexRT[Btn8R];
#define LINE_THRESHOLD 1000
			bool lineOnBL = SensorValue[lineBL] > LINE_THRESHOLD;
			bool lineOnBR = SensorValue[lineBR] > LINE_THRESHOLD;
			bool lineOnCL = SensorValue[lineCL] > LINE_THRESHOLD;
			bool lineOnCR = SensorValue[lineCR] > LINE_THRESHOLD;

			// Ch3: forward/backward
			word ch3 = vexRT[Ch3];
			if (abs(ch3)<10) ch3 = 0;
			fl = bl = ch3;
			fr = br = ch3;

			// Ch1: quick turn (rotate)
			word ch1 = lineMode? (lineOnBL? 127 : lineOnBR? -127 : 0) : vexRT[Ch1];
			if (abs(ch1)<10) ch1 = 0;
			fl += ch1; bl += ch1;
			fr -= ch1; br -= ch1;

			// Ch4: strafe
			word ch4 = lineMode? (lineOnCR? 127 : lineOnCL? -127 : 0) : vexRT[Ch4];
			if (abs(ch4)<10) ch4 = 0;
			fl += ch4; br += ch4;
			fr -= ch4; bl -= ch4;

			// set target control values (capping to [-127,127])
			IF_NPID(motor[driveFL]=) flSpd = fl<-127? -127 : fl>127? 127 : fl;//flSpd = 127;
		  IF_NPID(motor[driveFR]=) frSpd = fr<-127? -127 : fr>127? 127 : fr;
			IF_NPID(motor[driveBL]=) blSpd = bl<-127? -127 : bl>127? 127 : bl;
			IF_NPID(motor[driveBR]=) brSpd = br<-127? -127 : br>127? 127 : br;//flSpd=frSpd=blSpd=brSpd = 127;
		}

		//// OTHER CONTROLS ////
		{
			// hold 6U/D to turn on intake
			motor[intake] = vexRT[Btn6U]? 127 : vexRT[Btn6D]? -127 : 0;
			// hold 5U/D to turn on hopper
			motor[hopper] = vexRT[Btn5U]? 127 : vexRT[Btn5D]? -127 : 0;
			// hold 7L/R to turn on lift
			motor[lift1] = motor[lift2] = vexRT[Btn7L]? 127 : vexRT[Btn7R]? -127 : 0;

			// press 7D/7U to turn flywheel on/off, respectively
			if (vexRT[Btn7U]) turnFlywheelOn = true;
			if (vexRT[Btn7D]) turnFlywheelOn = false;

			// press 8D/8U to increment/decrement flywheel speed
			if (!prev8U && vexRT[Btn8U]) flywheelSpeed += 8;
			if (!prev8D && vexRT[Btn8D]) flywheelSpeed -= 8;
			prev8U = (bool)vexRT[Btn8U];
			prev8D = (bool)vexRT[Btn8D];
			if(flywheelSpeed<0)flywheelSpeed=0;if(flywheelSpeed>127)flywheelSpeed=127; // clamp to [0,127]
			IF_NPID(motor[flywheel1] = motor[flywheel2] = turnFlywheelOn? flywheelSpeed : 0;)
		}

		//UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	} // end of main while loop
} // end of usercontrol task
